Refactor SQS functionality and add new high-level methods
MITLibraries/dspace-submission-composer pull request #33
Opened 2024-12-19 21:37 UTC by ehanson8

### Purpose and background context
After trying to create higher-level methods, it became clear that the SQS functionality copied from `wiley-deposits` needed to be refactored.

### How can a reviewer manually see the effects of these changes?
Not possible yet

### Includes new or updated dependencies?
NO

### Changes expectations for external applications?
NO

### What are the relevant tickets?
- https://mitlibraries.atlassian.net/browse/IN-1128

### Developer
- [x] All new ENV is documented in README
- [x] All new ENV has been added to staging and production environments
- [x] All related Jira tickets are linked in commit message(s)
- [x] Stakeholder approval has been confirmed (or is not needed)

### Code Reviewer(s)
- [ ] The commit message is clear and follows our guidelines (not just this PR message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The provided documentation is sufficient for understanding any new functionality introduced
- [ ] Any manual tests have been performed **or** provided examples verified
- [ ] New dependencies are appropriate or there were no changes

2025-01-02 14:20 UTC, ghukill approved these changes
Seems like a good time to tackle some of these renamings and type tweaks (e.g. when required vs optional).  Looks good!

2025-01-02 15:01 UTC, ehanson8 commented on dsc/utilities/aws/sqs.py
> +            submission_system: The system where the submission is uploaded
Good call, adding it!

2025-01-03 18:33 UTC, jonavellecuerdo requested changes
Looking good! I have a few potential change requests.

2025-01-03 18:37 UTC, ehanson8 commented on dsc/item_submission.py
> +    def upload_dspace_metadata(self, bucket: str, s3_prefix: str) -> None:
Should this actually be `batch_path` for consistency with the `BaseWorkflow` property?

2025-01-03 18:39 UTC, ehanson8 commented on dsc/item_submission.py
> +            region=os.environ["AWS_REGION_NAME"], queue_name=os.environ["DSS_INPUT_QUEUE"]
Sounds great, go ahead and create the ticket! I did this because the `Config` class hadn't been implemented at the CLI-level yet

2025-01-03 18:39 UTC, ehanson8 commented on dsc/utilities/aws/sqs.py
> +            "PackageID": {"DataType": "String", "StringValue": identifier},
Great catch, fixed!

2025-01-03 18:42 UTC, ehanson8 commented on dsc/utilities/aws/sqs.py
> +            submission_system: The system where the submission is uploaded
Yes, I hadn't pushed the commit until the merge conflict fix

2025-01-03 18:47 UTC, jonavellecuerdo commented on dsc/item_submission.py
> +    def upload_dspace_metadata(self, bucket: str, s3_prefix: str) -> None:
I was reflecting on that a bit 🤔 While both the clients will be opinionated towards DSC in general, keeping it as "prefix" keeps some of the AWS semantics, which appeals to me for some reason...Maybe because it doesn't tie it too strictly with the `BaseWorkflow` class?

2025-01-03 18:49 UTC, jonavellecuerdo commented on dsc/item_submission.py
> +            region=os.environ["AWS_REGION_NAME"], queue_name=os.environ["DSS_INPUT_QUEUE"]
Ticket created: [IN-1140](https://mitlibraries.atlassian.net/browse/IN-1140)

2025-01-03 18:57 UTC, jonavellecuerdo approved these changes
Nice! 🎉

2025-01-03 18:59 UTC, merged